# Generated by Django 4.0.4 on 2022-04-28 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 18, 16, 9, 598847, tzinfo=utc), verbose_name='Date(dd/mm/yyyy) Time(hh:mm)'),
        ),
        migrations.AlterField(
            model_name='traveldetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
