# Generated by Django 3.2.13 on 2022-04-28 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_traveldetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 18, 44, 46, 37175, tzinfo=utc), verbose_name='Date(dd/mm/yyyy) Time(hh:mm)'),
        ),
    ]
